/*
 * MattApplet.java
 *
 * Created on 08 January 2009, 22:18
 */

package matt.web;

import abc.midi.*;
import javax.sound.midi.*;
import abc.parser.TuneBook;
import java.awt.event.*;
import javax.swing.*;
import java.io.*;
import java.awt.*;
import javax.swing.table.*;
import java.util.*;
import abc.notation.Tune;
import javax.swing.plaf.ColorUIResource;


import abc.midi.*;
import java.awt.Color;
import java.net.MalformedURLException;
import java.util.logging.Level;
import javax.swing.JProgressBar;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import matt.Graph;
import java.io.*;
import java.net.URLEncoder;
import javax.sound.sampled.*;
import matt.*;

/**
 *
 * @author  Bryan Duggan
 */
public class MattApplet extends javax.swing.JApplet implements matt.GUI {
    
    static public MattApplet _instance;
    Capture capture = new Capture();
    Playback playback = new Playback();
    AudioInputStream audioInputStream;
    String errStr;
    AudioFormat format = null;  
    final int bufSize = 16384;
    double duration, seconds;
    Transcriber transcriber = new Transcriber();
	
    float[] signal;
    
    private TunePlayer tunePlayer = new TunePlayer();
    
    private int sampleRate;
    private int numSamples;    
    byte[] audioData;

    public MattApplet()
    {

        _instance = this;
    }
    
    private void myInit()
    {
        // Add the graphs...
        signalGraph.setBounds(10,10,540,120);
        getContentPane().add(signalGraph);
        setBounds(0, 0, 560, 300);
        signalGraph.setBackground(Color.CYAN);
        format = new AudioFormat(44100, 16, 1, true, false);
        transcriber.setGui(this);
        
        MattProperties.instance(false).setProperty("drawFFTGraphs", "false");
        MattProperties.instance(false).setProperty("drawODFGraphs", "false");
        MattProperties.instance(false).setProperty("tansey", "false");
        MattProperties.instance(false).setProperty("applet", "true");
        _instance = this;
        
        tunePlayer.addListener(new TunePlayerAdapter()
        {
            public void playEnd(PlayerStateChangeEvent e)
            {
                btnPlayTranscribed.setText("Play Transcribed");
            }

        });
    }


    /** Initializes the applet MattApplet */
    public void init() {
        MattProperties.instance(true);
        signalGraph = new Graph();
        tunePlayer.start();
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    try 
                    {
                        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    } 
                    catch(Exception e) 
                    {
                        System.out.println("Error setting native LAF: " + e);
                    }
                    initComponents();
                    myInit();

                }

            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRecord = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnTranscribe = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtABC = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        txtStatus = new javax.swing.JLabel();
        btnPlayTranscribed = new javax.swing.JButton();
        btnOptions = new javax.swing.JButton();

        btnRecord.setText("Record");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });

        btnPlay.setText("Play Recording");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnFind.setText("Search!");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnTranscribe.setText("Transcribe");
        btnTranscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscribeActionPerformed(evt);
            }
        });

        txtABC.setColumns(20);
        txtABC.setLineWrap(true);
        txtABC.setRows(5);
        jScrollPane2.setViewportView(txtABC);

        jLabel2.setText("ABC Transcription:");

        txtStatus.setText("<Press record to begin!>");

        btnPlayTranscribed.setText("Play Transcribed");
        btnPlayTranscribed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayTranscribedActionPerformed(evt);
            }
        });

        btnOptions.setText("Options");
        btnOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnOptions)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFind))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnRecord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnTranscribe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlayTranscribed)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFind, btnOptions, btnPlay, btnPlayTranscribed, btnRecord, btnTranscribe});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRecord)
                            .addComponent(btnPlay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTranscribe)
                            .addComponent(btnPlayTranscribed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOptions)
                            .addComponent(btnFind)))
                    .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStatus)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents
	
private void btnFindActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFindActionPerformed
	{//GEN-HEADEREND:event_btnFindActionPerformed
    /*
     String url = "" + MattApplet._instance.getDocumentBase();
    url = url.substring(0, url.lastIndexOf("/")) + "/";
    url += "search.php?q=" + URLEncoder.encode(txtABC.getText());
     */
    String toFind = txtABC.getText();
    toFind = MattABCTools.expandLongNotes(toFind);
    toFind = MattABCTools.stripWhiteSpace(toFind);
    toFind = MattABCTools.stripBarDivisions(toFind);
    toFind = toFind.toUpperCase();

    String url = "http://www.comp.dit.ie/matt2/search.jsp?q=" + URLEncoder.encode(toFind);
    
    System.out.println("URL" + url);
    try
    {
        getAppletContext().showDocument(new java.net.URL(url), "results");
    }
    catch (MalformedURLException ex)
    {
        Logger.log(ex.toString());
    }
	}//GEN-LAST:event_btnFindActionPerformed


private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {                                          
    if (btnRecord.getText().equals("Record"))
    {
        capture.start();
        btnRecord.setText("Stop");
    }
    else
    {
        // lines.removeAllElements();
        capture.stop();
        btnRecord.setText("Record");
		
        try
        {
            synchronized(capture)
            {
                capture.wait();
            }
            AudioFormat format = audioInputStream.getFormat();
        
            numSamples = (int) audioInputStream.getFrameLength();
            audioData = new byte[(int) numSamples * 2];
            signal = new float[numSamples];
            audioInputStream.read(audioData, 0, (int) numSamples * 2);

            sampleRate = (int) format.getSampleRate();
            transcriber.setSampleRate(sampleRate);
            boolean bigEndian = format.isBigEndian();
            // Copy the signal from the file to the array
            getProgressBar().setValue(0);
            getProgressBar().setMaximum(numSamples);
            for (int signalIndex = 0; signalIndex < numSamples; signalIndex++)
            {
                signal[signalIndex] = ((audioData[(signalIndex * 2) + 1] << 8) + audioData[signalIndex * 2]);                                             
                getProgressBar().setValue(signalIndex);
            }
            
            Logger.log("Removing silence at the start...");
            transcriber.setSignal(signal);
            transcriber.removeSilence();           
            signal = transcriber.getSignal();
            Logger.log("Graphing...");
            if (Boolean.parseBoolean("" + MattProperties.getString("drawSignalGraphs")) == true)
            {
                signalGraph.getDefaultSeries().setData(signal);
                signalGraph.getDefaultSeries().setGraphType(Series.LINE_GRAPH);

                signalGraph.repaint();
            }
            Logger.log("Done.");
        }
        catch(Exception e)
        {
            e.printStackTrace();
            Logger.log("Could not plot audio: " + e.getMessage());
        }
    }
}                                         

private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
    if (btnPlay.getText().equals("Play Recording"))
    {
        playback.start();
        btnPlay.setText("Stop");
    }
    else
    {
        playback.stop();
        btnPlay.setText("Play Recording");
    }
}//GEN-LAST:event_btnPlayActionPerformed

private void btnTranscribeActionPerformed(java.awt.event.ActionEvent evt) {                                              
        try
        {            
            transcriber.setInputFile("");
            transcriber.transcribea();
        }
        catch (Exception ex)
        {
            Logger.log(ex.toString());
            ex.printStackTrace();
        }
}

private void btnPlayTranscribedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayTranscribedActionPerformed
        if (tunePlayer.isPlaying())
        {
            tunePlayer.stopPlaying();
            btnPlayTranscribed.setText("Play Transcribed");
            return;
        }        
        try 
        {
            btnPlayTranscribed.setText("Stop");
            StringBuffer tuneText = new StringBuffer();
            tuneText.append("X:1\r\n");
            tuneText.append("T:Temp\r\n");
            tuneText.append("R:Reel\r\n");
            tuneText.append("M:C|\r\n");
            tuneText.append("L:1/8\r\n");
            tuneText.append("K:D\r\n");
            tuneText.append(getTxtABC().getText());
            TuneBook book = new TuneBook();
            book.putTune(tuneText.toString());            
            Tune aTune = book.getTune(1);
            tunePlayer.play(aTune);            
        } 
        catch (Exception e)
        {
            e.printStackTrace();
        }       

}//GEN-LAST:event_btnPlayTranscribedActionPerformed

private void btnOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsActionPerformed
    
    Options.instance().setVisible(true);
}//GEN-LAST:event_btnOptionsActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnOptions;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlayTranscribed;
    private javax.swing.JButton btnRecord;
    private javax.swing.JButton btnTranscribe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextArea txtABC;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
    private Graph signalGraph;
    
    public class Playback implements Runnable {

        SourceDataLine line;
        Thread thread;

        public void start() {
            thread = new Thread(this);
            thread.setName("Playback");
            thread.start();
        }

        public void stop() {
            thread = null;
        }
        
        private void shutDown(String message) {
            if ((errStr = message) != null) {
                System.err.println(errStr);
                signalGraph.repaint();
            }
            if (thread != null) {
                thread = null;
                /*
                captB.setEnabled(true);
                pausB.setEnabled(false);
                playB.setText("Play");
                 */
                btnPlay.setText("Play Recording");
            } 
        }

        public void run() {

            // make sure we have something to play
            if (audioInputStream == null) {
                shutDown("No loaded audio to play back");
                return;
            }
            // reset to the beginnning of the stream

             try {
                audioInputStream.reset();
            } catch (Exception e) {
                e.printStackTrace();
                shutDown("Unable to reset the stream\n" + e);
                
                return;
            }

            AudioInputStream playbackInputStream = AudioSystem.getAudioInputStream(format, audioInputStream);
                        
            if (playbackInputStream == null) {
                shutDown("Unable to convert stream of format " + audioInputStream + " to format " + format);
                return;
            }

            // define the required attributes for our line, 
            // and make sure a compatible line is supported.

            DataLine.Info info = new DataLine.Info(SourceDataLine.class, 
                format);
            if (!AudioSystem.isLineSupported(info)) {
                shutDown("Line matching " + info + " not supported.");
                return;
            }

            // get and open the source data line for playback.

            try {
                line = (SourceDataLine) AudioSystem.getLine(info);
                line.open(format, bufSize);
            } catch (LineUnavailableException ex) { 
                shutDown("Unable to open the line: " + ex);
                return;
            }

            // play back the captured audio data

            int frameSizeInBytes = format.getFrameSize();
            int bufferLengthInFrames = line.getBufferSize() / 8;
            int bufferLengthInBytes = bufferLengthInFrames * frameSizeInBytes;
            byte[] data = new byte[bufferLengthInBytes];
            int numBytesRead = 0;

            // start the source data line
            line.start();

            while (thread != null) {
                try {
                    if ((numBytesRead = playbackInputStream.read(data)) == -1) {
                        break;
                    }
                    int numBytesRemaining = numBytesRead;
                    while (numBytesRemaining > 0 ) {
                        numBytesRemaining -= line.write(data, 0, numBytesRemaining);
                    }
                } catch (Exception e) {
                    shutDown("Error during playback: " + e);
                    break;
                }
            }
            // we reached the end of the stream.  let the data play out, then
            // stop and close the line.
            if (thread != null) {
                line.drain();
            }
            line.stop();
            line.close();
            line = null;
            shutDown(null);
        }
    } // End class Playback
        

    /** 
     * Reads data from the input channel and writes to the output stream
     */
    class Capture implements Runnable {

        TargetDataLine line;
        Thread thread;

        public void start() {
            errStr = null;
            thread = new Thread(this);
            thread.setName("Capture");
            thread.start();
        }

        public void stop() {
            thread = null;
        }
        
        private void shutDown(String message) {
            System.out.println(message);
            if ((errStr = message) != null && thread != null) {
                thread = null;
            }
        }

        
        public void run() {

            duration = 0;
            audioInputStream = null;
            System.out.println("0");

            // define the required attributes for our line, 
            // and make sure a compatible line is supported.
         
            DataLine.Info info = new DataLine.Info(TargetDataLine.class, 
                format);
            System.out.println("1");
            if (!AudioSystem.isLineSupported(info)) {
                shutDown("Line matching " + info + " not supported.");
                return;
            }
            System.out.println("2");
            // get and open the target data line for capture.
            try {
                line = (TargetDataLine) AudioSystem.getLine(info);
                line.open(format, line.getBufferSize());
            } catch (LineUnavailableException ex) { 
                shutDown("Unable to open the line: " + ex);
                return;
            } catch (SecurityException ex) { 
                shutDown(ex.toString());
                // showInfoDialog();
                return;
            } catch (Exception ex) { 
                shutDown(ex.toString());
                return;
            }
            
            System.out.println("3");
            // play back the captured audio data
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            int frameSizeInBytes = format.getFrameSize();
            int bufferLengthInFrames = line.getBufferSize() / 8;
            int bufferLengthInBytes = bufferLengthInFrames * frameSizeInBytes;
            byte[] data = new byte[bufferLengthInBytes];
            int numBytesRead;
            
            line.start();
            System.out.println("4");
            while (thread != null) {
                if((numBytesRead = line.read(data, 0, bufferLengthInBytes)) == -1) {
                    break;
                }
                out.write(data, 0, numBytesRead);
            }

            // we reached the end of the stream.  stop and close the line.
            line.stop();
            line.close();
            line = null;

            // stop and close the output stream
            try {
                out.flush();
                out.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }

            // load bytes into the audio input stream for playback

            byte audioBytes[] = out.toByteArray();
            ByteArrayInputStream bais = new ByteArrayInputStream(audioBytes);
            audioInputStream = new AudioInputStream(bais, format, audioBytes.length / frameSizeInBytes);

            long milliseconds = (long)((audioInputStream.getFrameLength() * 1000) / format.getFrameRate());
            duration = milliseconds / 1000.0;

            try {
                audioInputStream.reset();
            } catch (Exception ex) { 
                ex.printStackTrace(); 
                return;
            }
            synchronized(this)
            {
                notify();
            }
            // signalGraph.getDefaultSeries().setData(audioBytes);
        }
    } // End class Capture

    public void clearGraphs()
    {
        signalGraph.clear();
    }

    public Graph getSignalGraph()
    {
        return signalGraph;
    }

    public Graph getOdfGraph()
    {
        return null;
    }

    public JProgressBar getProgressBar()
    {
        return progressBar;
    }

    public void setTitle(String t)
    {
        
    }

    public void enableButtons(boolean b)
    {
        btnRecord.setEnabled(b);
        btnPlayTranscribed.setEnabled(b);
        btnOptions.setEnabled(b);
        btnFind.setEnabled(b);
        btnPlay.setEnabled(b);
        btnTranscribe.setEnabled(b);
    }

    public void clearFFTGraphs()
    {
        
    }

    public Graph getFrameGraph()
    {
        return null;
    }

    public JTextArea getTxtABC()
    {
        return txtABC;
    }
    
    public static void setStatus(String msg)
    {
        _instance.txtStatus.setText(msg);
    }
}
