/*
 * MattApplet.java
 *
 * Created on 08 January 2009, 22:18
 */

package matt.web;

import abc.parser.TuneBook;
import java.awt.event.*;
import javax.swing.*;
import abc.notation.Tune;
import abc.midi.*;
import java.awt.Color;
import java.net.MalformedURLException;
import javax.swing.JProgressBar;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import java.io.*;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.TimerTask;
import java.util.Timer;
import javax.sound.sampled.*;
import javax.swing.UIManager.LookAndFeelInfo;
import matt.*;


/**
 *
 * @author  Bryan Duggan
 */


public class MattApplet extends javax.swing.JApplet implements matt.GUI {

    static public MattApplet _instance;
    Capture capture = new Capture();
    Playback playback = new Playback();
    AudioInputStream audioInputStream;
    String errStr;
    AudioFormat format = null;  
    final int bufSize = 16384;
    double duration, seconds;
    ODCFTranscriber transcriber = new ODCFTranscriber();
	
    float[] signal;
    
    private TunePlayer tunePlayer = new TunePlayer();
    
    private int sampleRate;
    private int numSamples;    
    byte[] audioData;

    public MattApplet()
    {

        _instance = this;
    }

    private void myInit()
    {
        // Add the graphs...
        signalGraph.setBounds(10,10,getBounds().width - 20 ,80);
        setBackground(new Color(249,249,249));

        /*
         Dimension d = new Dimension();
        d.width = getBounds().width - 20;
        d.height = txtStatus.getSize().height;

        txtStatus.setSize(d);
        txtStatus.setPreferredSize(d);
        */
       
        getContentPane().add(signalGraph);
        //setBounds(0, 0, 630, 300);
        signalGraph.setBackground(new Color(176,210,13));
        format = new AudioFormat(44100, 16, 1, true, false);
        transcriber.setGui(this);
        theCorpusList.setGui(this);
        theTypeList.setGui(this);

        MattProperties.instance(false).setProperty("drawFFTGraphs", "false");
        MattProperties.instance(false).setProperty("drawODFGraphs", "false");
        MattProperties.instance(false).setProperty("tansey", "false");
        MattProperties.instance(false).setProperty("applet", "true");
        _instance = this;
        
        tunePlayer.addListener(new TunePlayerAdapter()
        {
            public void playEnd(PlayerStateChangeEvent e)
            {
               // playABCbtn.setText("Play ABC");
            }

        });
        cmbFundamental.setSelectedItem(MattProperties.instance().getString("fundamentalNote"));
    }


    /** Initializes the applet MattApplet */
    public void init() {
        MattProperties.instance(true);
        setBackground(new Color(249,249,249));
        signalGraph = new Graph();
        tunePlayer.start();
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    try {
                        for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                            if ("Nimbus".equals(info.getName())) {
                                UIManager.setLookAndFeel(info.getClassName());
                                break;
                            }
                        }
                    } catch (UnsupportedLookAndFeelException e) {
                        // handle exception
                    } catch (ClassNotFoundException e) {
                        // handle exception
                    } catch (InstantiationException e) {
                        // handle exception
                    } catch (IllegalAccessException e) {
                        // handle exception
                    }
                    initComponents();
                    myInit();

                }

            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void windowClosing(WindowEvent e) {
        
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFind = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        btnRecord = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        slSilence = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        cmbFundamental = new javax.swing.JComboBox();
        btnTranscribe = new javax.swing.JButton();
        txtStatus = new javax.swing.JLabel();
        TuneBookBtn = new javax.swing.JButton();
        TuneTypeBtn = new javax.swing.JButton();
        playABCbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtABC = new javax.swing.JTextArea();
        progressBar = new javax.swing.JProgressBar();
        btnFind1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbTranscriber = new javax.swing.JComboBox();

        btnFind.setText("Search!");
        btnFind.setMaximumSize(new java.awt.Dimension(32767, 32767));
        btnFind.setMinimumSize(new java.awt.Dimension(73, 18));
        btnFind.setPreferredSize(new java.awt.Dimension(78, 20));
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(249, 249, 249));

        jPanel1.setFocusable(false);
        jPanel1.setOpaque(false);

        btnPlay.setText("Playback");
        btnPlay.setEnabled(false);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnRecord.setText("Record");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });

        jLabel6.setText("Silence threshold:");

        slSilence.setMaximum(6000);
        slSilence.setValue(1500);

        jLabel1.setText("Fundamental:");

        cmbFundamental.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bb", "C", "D", "Eb", "F", "G" }));
        cmbFundamental.setName("cmbFundamental"); // NOI18N
        cmbFundamental.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFundamentalItemStateChanged(evt);
            }
        });
        cmbFundamental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFundamentalActionPerformed(evt);
            }
        });

        btnTranscribe.setText("Transcribe");
        btnTranscribe.setEnabled(false);
        btnTranscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscribeActionPerformed(evt);
            }
        });

        txtStatus.setText("<Press record to begin!>");
        txtStatus.setMaximumSize(new java.awt.Dimension(68, 14));
        txtStatus.setMinimumSize(new java.awt.Dimension(68, 14));
        txtStatus.setPreferredSize(new java.awt.Dimension(68, 20));

        TuneBookBtn.setText("Tune Books: ...");
        TuneBookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TuneBookBtnMouseClicked(evt);
            }
        });

        TuneTypeBtn.setText("Tune Types: ...");
        TuneTypeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TuneTypeBtnMouseClicked(evt);
            }
        });
        TuneTypeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuneTypeBtnActionPerformed(evt);
            }
        });

        playABCbtn.setText("Play ABC");
        playABCbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playABCbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slSilence, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTranscribe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(btnRecord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                        .addComponent(cmbFundamental, 0, 96, Short.MAX_VALUE))
                                    .addComponent(playABCbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TuneTypeBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(TuneBookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPlay, btnRecord, btnTranscribe, jLabel1, jLabel6, playABCbtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(slSilence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbFundamental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTranscribe)
                            .addComponent(playABCbtn)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRecord)
                        .addComponent(btnPlay)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TuneBookBtn)
                .addGap(5, 5, 5)
                .addComponent(TuneTypeBtn)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPlay, btnRecord, btnTranscribe, cmbFundamental, playABCbtn});

        jPanel2.setFocusable(false);
        jPanel2.setOpaque(false);

        jLabel2.setText("ABC to search for:");

        txtABC.setColumns(20);
        txtABC.setLineWrap(true);
        txtABC.setRows(5);
        jScrollPane2.setViewportView(txtABC);

        btnFind1.setText("Search!");
        btnFind1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        btnFind1.setMinimumSize(new java.awt.Dimension(73, 18));
        btnFind1.setPreferredSize(new java.awt.Dimension(78, 20));
        btnFind1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFind1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(progressBar, 0, 0, Short.MAX_VALUE))
                    .addComponent(btnFind1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFind1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        cmbTranscriber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Method 1", "Method 2" }));
        cmbTranscriber.setOpaque(false);
        cmbTranscriber.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTranscriberItemStateChanged(evt);
            }
        });
        cmbTranscriber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTranscriberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1206, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTranscriber, 0, 87, Short.MAX_VALUE)
                .addGap(1408, 1408, 1408))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTranscriber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
	
private void btnFindActionPerformed(ActionEvent evt)//GEN-FIRST:event_btnFindActionPerformed
	{//GEN-HEADEREND:event_btnFindActionPerformed
    /*
     String url = "" + MattApplet._instance.getDocumentBase();
    url = url.substring(0, url.lastIndexOf("/")) + "/";
    url += "search.php?q=" + URLEncoder.encode(txtABC.getText());
     */
    String toFind = txtABC.getText();
    toFind = MattABCTools.expandLongNotes(toFind);
    toFind = MattABCTools.stripWhiteSpace(toFind);
    toFind = MattABCTools.stripBarDivisions(toFind);
    toFind = toFind.toUpperCase();


    String docBase = "" + getDocumentBase();
    int li = docBase.lastIndexOf("/");
    String url = docBase.substring(0, li) + "/search8.jsp?version=1.4&q=" + URLEncoder.encode(toFind);
    System.out.println(url);
    //String url = "http://localhost:8080/MattWeb/search8.jsp?q=" + URLEncoder.encode(toFind);
    //String url = "http://skooter500.s156.eatj.com/MattWeb/search.jsp?q=" + URLEncoder.encode(toFind);
    //String url = "http://www.comp.dit.ie/matt2/search8.jsp?q=" + URLEncoder.encode(toFind);
  //  url += "&corpus=" + (cmbCorpus.getSelectedIndex());
    //url += "&corpus=" + theCorpusList.getVals();
    //System.out.println(theCorpusList.getVals());
//    url += "&type=" + cmbType.getSelectedItem();
    //url += "&type=" + theTypeList.getVals();
    url += "&silence=" + (int) slSilence.getValue();
    url += "&method=" + cmbTranscriber.getSelectedItem();
    System.out.println("URL: " + url);
    try
    {
        getAppletContext().showDocument(new java.net.URL(url), "results");
    }
    catch (MalformedURLException ex)
    {
        Logger.log(ex.toString());
    }
	}//GEN-LAST:event_btnFindActionPerformed


class RemindTask extends TimerTask {
    int secleft = 15;
    int countup = 1;
    public void run() {
          if (secleft > 12) {
            txtStatus.setText("Recording in " + (secleft-12) + "...");
            btnRecord.setText("Stop");
            secleft--;
          }
          else if (secleft == 12) {
            btnRecord.setText("Recording in 0...");
            getProgressBar().setValue(0);
            getProgressBar().setMaximum(12);
            countdown= false;
            recording = true;
            secleft--;
            countup++;
            btnRecord.setText("Record");
            record();
          }
          else if (secleft > 0) {
            //btnRecord.setText("Stop");
            txtStatus.setText("Recording!");
            getProgressBar().setValue(countup);
            secleft--;
            countup++;
          }
          else {
            //btnRecord.setText("Record");
            countdown = false;
            recording = false;
            record();
            this.cancel();
          }
    }
  }

public boolean countdown = false;
public boolean recording = false;
public Timer cdtimer;
public CheckList theCorpusList = new CheckList(new String[]
    {"All", "thesession.org", "Norbeck", "O'Neill's 1001", "Ceol Rince na hÉireann 1",
     "Ceol Rince na hÉireann 2", "Ceol Rince na hÉireann 3", "Ceol Rince na hÉireann 4",
     "Johnny O'Leary", "Nigel Gatherer", "The Microphone Rambles", "John Tose", "Jack Campin",
     "Fife and Drum", "Nottingham Database", "Aird's Airs"});

public CheckList theTypeList = new CheckList(new String[]
    {"All", "Reel", "Jig", "Slip Jig", "Slide", "March", "Mazurka", "Polka", "Hop",
     "Barndance", "Double Jig", "Single Jig", "Fling", "Halling", "Highland", "Hornpipe",
     "Set dance", "Polska J", "Polska K1", "Polska L1", "Polska O", "Strathspey",
     "Three-two", "Waltz"});

public String corpString = "";
public String typeString = "";


private void btnRecordActionPerformed(ActionEvent evt) {
    //theCorpusList.setVisible(true);
    
    //Timer recTimer = new Timer();
    if (btnRecord.getText().equals("Record"))
    {
        cdtimer = new Timer();
        countdown = true;
        btnRecord.setText("Stop");
        cdtimer.schedule(new RemindTask(), 0, 1 * 1000);
        //recTimer.schedule(new StartTask(), 0, 1 * 1000);
    }
    else if (countdown || recording)
    {
        txtStatus.setText("<Press record to begin!>");
        cdtimer.cancel();
        cdtimer.purge();
        cdtimer = null;
        countdown = false;
        recording = false;
        getProgressBar().setValue(0);
        btnRecord.setText("Record");
    }
    else
    {
        countdown = false;
        recording = false;
        cdtimer.cancel();
        cdtimer.purge();
        cdtimer = null;
        getProgressBar().setValue(0);
        txtStatus.setText("<Press record to begin!>");
        cdtimer.cancel();
        record();
    }
}



private void record() {
    //timer.cancel();
    if (btnRecord.getText().equals("Record"))
    {
        signalGraph.getDefaultSeries().clearLines();
        signalGraph.getDefaultSeries().clear();
        txtABC.setText("");
        capture.start();
        btnRecord.setText("Stop");
    }
    else
    {
        // lines.removeAllElements();
        capture.stop();
        btnRecord.setText("Record");
		
        try
        {
            synchronized(capture)
            {
                capture.wait();
            }
            AudioFormat format = audioInputStream.getFormat();
        
            numSamples = (int) audioInputStream.getFrameLength();
            audioData = new byte[(int) numSamples * 2];
            signal = new float[numSamples];
            audioInputStream.read(audioData, 0, (int) numSamples * 2);

            sampleRate = (int) format.getSampleRate();
            transcriber.setSampleRate(sampleRate);
            boolean bigEndian = format.isBigEndian();
            // Copy the signal from the file to the array
            getProgressBar().setValue(0);
            getProgressBar().setMaximum(numSamples);
            for (int signalIndex = 0; signalIndex < numSamples; signalIndex++)
            {
                signal[signalIndex] = ((audioData[(signalIndex * 2) + 1] << 8) + audioData[signalIndex * 2]);                                             
                getProgressBar().setValue(signalIndex);
                //System.out.println(signal[signalIndex]);
            }
            
            Logger.log("Removing silence at the start...");
            transcriber.setSignal(signal);
            transcriber.setSilenceThreshold(slSilence.getValue());
            transcriber.removeSilence();           
            signal = transcriber.getSignal();
            Logger.log("Graphing...");
            if (Boolean.parseBoolean("" + MattProperties.getString("drawSignalGraphs")) == true)
            {
                signalGraph.getDefaultSeries().setData(signal);
                signalGraph.getDefaultSeries().setGraphType(Series.LINE_GRAPH);

                signalGraph.repaint();
            }
            getProgressBar().setValue(0);
            Logger.log("Done.");
            btnPlay.setEnabled(true);
            btnTranscribe.setEnabled(true);
        }
        catch(Exception e)
        {
            e.printStackTrace();
            Logger.log("Could not plot audio: " + e.getMessage());
            Logger.log("Could not hear the melody.");
            getProgressBar().setValue(0);
        }
    }
}                                         

private void btnPlayActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
    if (btnPlay.getText().equals("Playback"))
    {
        playback.start();
        btnPlay.setText("Stop");
    }
    else
    {
        playback.stop();
        btnPlay.setText("Playback");
    }
}//GEN-LAST:event_btnPlayActionPerformed

private void btnTranscribeActionPerformed(ActionEvent evt) {                                              
        try
        {

            txtABC.setText("");
            transcriber.setInputFile("");
            MattProperties.setString("fundamentalNote", "" + cmbFundamental.getSelectedItem());
            transcriber.transcribea();
            playABCbtn.setEnabled(true);
        }
        catch (Exception ex)
        {
            Logger.log(ex.toString());
            ex.printStackTrace();
        }
}

private void cmbFundamentalActionPerformed(ActionEvent evt)//GEN-FIRST:event_cmbFundamentalActionPerformed
{//GEN-HEADEREND:event_cmbFundamentalActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_cmbFundamentalActionPerformed

private void cmbFundamentalItemStateChanged(ItemEvent evt)//GEN-FIRST:event_cmbFundamentalItemStateChanged
{//GEN-HEADEREND:event_cmbFundamentalItemStateChanged
    MattProperties.setString("fundamentalNote", "" + cmbFundamental.getSelectedItem());
}//GEN-LAST:event_cmbFundamentalItemStateChanged

private void cmbTranscriberActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbTranscriberActionPerformed
{//GEN-HEADEREND:event_cmbTranscriberActionPerformed

}//GEN-LAST:event_cmbTranscriberActionPerformed

private void cmbTranscriberItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbTranscriberItemStateChanged
{//GEN-HEADEREND:event_cmbTranscriberItemStateChanged
    if (cmbTranscriber.getSelectedItem().equals("Method 1"))
    {
        transcriber = new ODCFTranscriber();
    }
    else
    {
        transcriber = new STFTTranscriber();
        
    }
    transcriber.setGui(this);
    transcriber.setSampleRate(sampleRate);
    if (signal != null)
    {
        transcriber.setSignal(signal);
    }
}//GEN-LAST:event_cmbTranscriberItemStateChanged

private void btnFind1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFind1ActionPerformed

    // set string to use as query
    String toFind = txtABC.getText();
    toFind = MattABCTools.expandLongNotes(toFind);
    toFind = MattABCTools.stripWhiteSpace(toFind);
    toFind = MattABCTools.stripBarDivisions(toFind);
    toFind = toFind.toUpperCase();

    
    String docBase = "" + getDocumentBase();
    int li = docBase.lastIndexOf("/");
    String url = docBase.substring(0, li) + "/search8.jsp?version=1.4&q=" + URLEncoder.encode(toFind);

    url += "&sources=";
    url += theCorpusList.getVals();
    url += "&types=";
    url += theTypeList.getVals();
//    ArrayList typeSrchList= theTypeList.getVals();
//    for (int i= 0; i < typeSrchList.size(); i++) {
//         url += "&type[]=";
//         url += typeSrchList.get(i);
//    }

//    ArrayList corpSrchList= theCorpusList.getVals();
//    for (int i= 0; i < corpSrchList.size(); i++) {
//         url += "&corpus[]=";
//         url += corpSrchList.get(i);
//    }
    
    url += "&silence=" + (int) slSilence.getValue();
    url += "&method=" + cmbTranscriber.getSelectedItem();
    System.out.println("URL: " + url);
    try {
        getAppletContext().showDocument(new java.net.URL(url), "results");
    } catch (MalformedURLException ex) {
        Logger.log(ex.toString());
    }
}//GEN-LAST:event_btnFind1ActionPerformed

private void TuneBookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TuneBookBtnMouseClicked
    theCorpusList.setVisible(true);
    theCorpusList.setLocationRelativeTo(null);
}//GEN-LAST:event_TuneBookBtnMouseClicked

private void TuneTypeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TuneTypeBtnMouseClicked
    theTypeList.setVisible(true);
    theTypeList.setLocationRelativeTo(null);
}//GEN-LAST:event_TuneTypeBtnMouseClicked

private void TuneTypeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuneTypeBtnActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_TuneTypeBtnActionPerformed

private void playABCbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playABCbtnActionPerformed
        if (tunePlayer.isPlaying())
        {
            tunePlayer.stopPlaying();
            //playABCbtn.setText("Play ABC");
            return;
        }
        try
        {
            //playABCbtn.setText("Stop");
            StringBuffer tuneText = new StringBuffer();
            tuneText.append("X:1\r\n");
            tuneText.append("T:Temp\r\n");
            tuneText.append("R:Reel\r\n");
            tuneText.append("M:C|\r\n");
            tuneText.append("L:1/8\r\n");
            tuneText.append("K:D\r\n");
            tuneText.append(getTxtABC().getText());
            TuneBook book = new TuneBook();
            book.putTune(tuneText.toString());
            Tune aTune = book.getTune(1);
            tunePlayer.play(aTune);
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }     // TODO add your handling code here:
}//GEN-LAST:event_playABCbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TuneBookBtn;
    private javax.swing.JButton TuneTypeBtn;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFind1;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnRecord;
    private javax.swing.JButton btnTranscribe;
    private javax.swing.JComboBox cmbFundamental;
    private javax.swing.JComboBox cmbTranscriber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton playABCbtn;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JSlider slSilence;
    private javax.swing.JTextArea txtABC;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
    private Graph signalGraph;

   
    public class Playback implements Runnable {

        SourceDataLine line;
        Thread thread;

        public void start() {
            thread = new Thread(this);
            thread.setName("Playback");
            thread.start();
        }

        public void stop() {
            thread = null;
        }
        
        private void shutDown(String message) {
            if ((errStr = message) != null) {
                System.err.println(errStr);
                signalGraph.repaint();
            }
            if (thread != null) {
                thread = null;
                /*
                captB.setEnabled(true);
                pausB.setEnabled(false);
                playB.setText("Play");
                 */
                btnPlay.setText("Playback");
            } 
        }

        public void run() {

            // make sure we have something to play
            if (audioInputStream == null) {
                shutDown("No loaded audio to play back");
                return;
            }
            // reset to the beginnning of the stream

             try {
                audioInputStream.reset();
            } catch (Exception e) {
                e.printStackTrace();
                shutDown("Unable to reset the stream\n" + e);
                
                return;
            }

            AudioInputStream playbackInputStream = AudioSystem.getAudioInputStream(format, audioInputStream);
                        
            if (playbackInputStream == null) {
                shutDown("Unable to convert stream of format " + audioInputStream + " to format " + format);
                return;
            }

            // define the required attributes for our line, 
            // and make sure a compatible line is supported.

            DataLine.Info info = new DataLine.Info(SourceDataLine.class, 
                format);
            if (!AudioSystem.isLineSupported(info)) {
                shutDown("Line matching " + info + " not supported.");
                return;
            }

            // get and open the source data line for playback.

            try {
                line = (SourceDataLine) AudioSystem.getLine(info);
                line.open(format, bufSize);
            } catch (LineUnavailableException ex) { 
                shutDown("Unable to open the line: " + ex);
                return;
            }

            // play back the captured audio data

            int frameSizeInBytes = format.getFrameSize();
            int bufferLengthInFrames = line.getBufferSize() / 8;
            int bufferLengthInBytes = bufferLengthInFrames * frameSizeInBytes;
            byte[] data = new byte[bufferLengthInBytes];
            int numBytesRead = 0;

            // start the source data line
            line.start();

            while (thread != null) {
                try {
                    if ((numBytesRead = playbackInputStream.read(data)) == -1) {
                        break;
                    }
                    int numBytesRemaining = numBytesRead;
                    while (numBytesRemaining > 0 ) {
                        numBytesRemaining -= line.write(data, 0, numBytesRemaining);
                    }
                } catch (Exception e) {
                    shutDown("Error during playback: " + e);
                    break;
                }
            }
            // we reached the end of the stream.  let the data play out, then
            // stop and close the line.
            if (thread != null) {
                line.drain();
            }
            line.stop();
            line.close();
            line = null;
            shutDown(null);
        }
    } // End class Playback
        

    /** 
     * Reads data from the input channel and writes to the output stream
     */
    class Capture implements Runnable {

        TargetDataLine line;
        Thread thread;

        public void start() {
            errStr = null;
            thread = new Thread(this);
            thread.setName("Capture");
            thread.start();
        }

        public void stop() {
            thread = null;
        }
        
        private void shutDown(String message) {
            System.out.println(message);
            if ((errStr = message) != null && thread != null) {
                thread = null;
            }
        }

        
        public void run() {

            duration = 0;
            audioInputStream = null;
            System.out.println("0");

            // define the required attributes for our line, 
            // and make sure a compatible line is supported.
         
            DataLine.Info info = new DataLine.Info(TargetDataLine.class, 
                format);
            System.out.println("1");
            if (!AudioSystem.isLineSupported(info)) {
                shutDown("Line matching " + info + " not supported.");
                return;
            }
            System.out.println("2");
            // get and open the target data line for capture.
            try {
                line = (TargetDataLine) AudioSystem.getLine(info);
                line.open(format, line.getBufferSize());
            } catch (LineUnavailableException ex) { 
                shutDown("Unable to open the line: " + ex);
                return;
            } catch (SecurityException ex) { 
                shutDown(ex.toString());
                // showInfoDialog();
                return;
            } catch (Exception ex) { 
                shutDown(ex.toString());
                return;
            }
            
            System.out.println("3");
            // play back the captured audio data
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            int frameSizeInBytes = format.getFrameSize();
            int bufferLengthInFrames = line.getBufferSize() / 8;
            int bufferLengthInBytes = bufferLengthInFrames * frameSizeInBytes;
            byte[] data = new byte[bufferLengthInBytes];
            int numBytesRead;
            
            line.start();
            System.out.println("4");
            while (thread != null) {
                if((numBytesRead = line.read(data, 0, bufferLengthInBytes)) == -1) {
                    break;
                }
                out.write(data, 0, numBytesRead);
            }

            // we reached the end of the stream.  stop and close the line.
            line.stop();
            line.close();
            line = null;

            // stop and close the output stream
            try {
                out.flush();
                out.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }

            // load bytes into the audio input stream for playback

            byte audioBytes[] = out.toByteArray();
            ByteArrayInputStream bais = new ByteArrayInputStream(audioBytes);
            audioInputStream = new AudioInputStream(bais, format, audioBytes.length / frameSizeInBytes);

            long milliseconds = (long)((audioInputStream.getFrameLength() * 1000) / format.getFrameRate());
            duration = milliseconds / 1000.0;

            try {
                audioInputStream.reset();
            } catch (Exception ex) { 
                ex.printStackTrace(); 
                return;
            }
            synchronized(this)
            {
                notify();
            }
            // signalGraph.getDefaultSeries().setData(audioBytes);
        }
    } // End class Capture

    public void clearGraphs()
    {
        signalGraph.clear();
    }

    public Graph getSignalGraph()
    {
        return signalGraph;
    }

    public Graph getOdfGraph()
    {
        return null;
    }

    public JProgressBar getProgressBar()
    {
        return progressBar;
    }

    public void setTitle(String t)
    {
        
    }

    public void enableButtons(boolean b)
    {
        btnRecord.setEnabled(b);
        playABCbtn.setEnabled(b);
        btnFind.setEnabled(b);
        btnPlay.setEnabled(b);
        btnTranscribe.setEnabled(b);
//        cmbCorpus.setEnabled(b);
        cmbFundamental.setEnabled(b);
    //    cmbType.setEnabled(b);
        txtABC.setEnabled(b);
        slSilence.setEnabled(b);
        cmbTranscriber.setEnabled(b);
    }

    public void clearFFTGraphs()
    {
        
    }

    public Graph getFrameGraph()
    {
        return null;
    }

    public JTextArea getTxtABC()
    {
        return txtABC;
    }
    
    public static void setStatus(String msg)
    {
        _instance.txtStatus.setText(msg);
    }

    public void setBns() {
        if (theCorpusList.getWhat().length() > 15)
            TuneBookBtn.setText("Tune Books: " + theCorpusList.getWhat().substring(0, 5) + "..." + theCorpusList.getWhat().substring((theCorpusList.getWhat().length() - 5)));
        else
            TuneBookBtn.setText("Tune Books: " + theCorpusList.getWhat());
        if (theTypeList.getWhat().length() > 15)
            TuneTypeBtn.setText("Tune Types: " + theTypeList.getWhat().substring(0, 5) + "..." + theTypeList.getWhat().substring((theTypeList.getWhat().length() - 5)));
        else
            TuneTypeBtn.setText("Tune Types: " + theTypeList.getWhat());
        }
}
