/*
 * About.java
 *
 * Created on 29 April 2008, 17:35
 */

package matt;

/**
 *
 * @author  Bryan Duggan
 */
public class About extends javax.swing.JFrame {
    private static About _instance = null;
    
    public static About instance()
    {
        if (_instance == null)
        {
            _instance = new About();
        }
        return _instance;
    }
    /** Creates new form About */
    public About() {
        initComponents();
        MattGuiNB.center(this, 300, 250);
    }
   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        lblText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 300, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                load(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setText("MATT2");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(121, 121, 121)
                .add(btnOk)
                .addContainerGap(154, Short.MAX_VALUE))
            .add(lblText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(lblText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void load(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_load
        StringBuffer text = new StringBuffer();
        text.append("<html><center><h3>MATT2 - Machine Annotation of Traditional Tunes</h3><br\\>");
        text.append("By Bryan Duggan<br\\>");
        text.append("School of Computing, DIT<br\\>");
        text.append("<a href=\"mailto:bryan.duggan@dit.ie\">bryan.duggan@dit.ie</a><br\\>");
        text.append("Using ABC files transcribed by Henrik Norbeck<br/><a href=\"http://www.norbeck.nu/abc/\">http://www.norbeck.nu/abc/</a><br\\>");
        text.append("Uses ABC4J by Lionel Gueganton<br\\>");
        text.append("<a href=\"http://code.google.com/p/abc4j\">http://code.google.com/p/abc4j</a><br/>");
        text.append("</center></html>");
        lblText.setText("" + text);
    }//GEN-LAST:event_load

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
    
}
